### ISSUE TITLE
WrappedRequests with same method names from different services return incorrect request schemas

### ISSUE THREAD

**Issue by DarrenMa** [abelsilva/swaggerwcf#107]
If two or more service methods have the same name (different services or UriTemplates) and have `BodyStyle = WebMessageBodyStyle.Wrapped` then the RequestWrapper schemas on the UI will load the same RequestWrapper schema example for each of those methods.

The original CreateAuthor model example value
![image](https://user-images.githubusercontent.com/6094383/31078419-60a22768-a782-11e7-8554-5144259eef95.png)

after the modification you can see the Create author model example value is displaying the `Book` model
![image](https://user-images.githubusercontent.com/6094383/31078487-a804f8d8-a782-11e7-90d4-ea418fac116c.png)

**To reproduce the issue:**
Change `Book CreateBook` to `Book Create` and 
```
        [WebInvoke(UriTemplate = "/authors", BodyStyle = WebMessageBodyStyle.Bare, Method = "POST",
            RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Xml)]
        [OperationContract]
        Author CreateAuthor(
            [SwaggerWcfParameter(Description = "Author to be created, the id will be replaced")] Author value);
``` 
to 
```
        [SwaggerWcfPath("Create author", "Create an author on the store")]
        [WebInvoke(UriTemplate = "/authors", BodyStyle = WebMessageBodyStyle.Wrapped, Method = "POST",
            RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Xml)]
        [OperationContract]
        Author Create(
            [SwaggerWcfParameter(Description = "Author to be created, the id will be replaced")] Author value);
```

The swagger.json outputs identical parameters for the two different methods.

```
                "parameters": [
                    {
                        "name": "CreateRequestWrapper",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateRequest"
                        }
                    }
                ],
```

**Comment by abelsilva** [comment]
can you check latest version? reopen if issue is still present

**Comment by DarrenMa** [comment]
@abelsilva the issue is still present in versions 1.29 and trunk.

**Comment by abelsilva** [comment]
ok, I didn't understand correctly the issue

I think I fixed it, but not in an automatic way, based on the information I can't guarantee different schemas for each function

you will be able to add 
```
        [SwaggerWcfReturnType(Name = "MyResult")]
```
to the methods in order to change the return type

I'll upload a new version later today

**Comment by DarrenMa** [comment]
I used `[SwaggerWcfReturnType(typeof(Author), "Author")]`.
The example/model under the Response is now correct. Great job!

But I noticed that the example/model by the parameter is still incorrect. Displaying the Book model.

![swag](https://user-images.githubusercontent.com/6094383/32369651-398d07c6-c08a-11e7-824a-32fa3f1d5698.PNG)

**Comment by abelsilva** [comment]
can you check now, also add to the functions the attribute:

```
        [SwaggerWcfRequestType(Name = "BookRequest")]
```

**Comment by abelsilva** [comment]
latest version `0.2.3` should be available shortly in nuget

**Comment by DarrenMa** [comment]
@abelsilva thanks it's working!
